/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package com.borak.hikingapp.commonlib.domain.enums;

/**
 *
 * @author Despot
 */
public enum ErrorType {
    FILE_NOT_FOUND_ERROR,
    IO_ERROR,
    CONNECTION_ESTABLISHING_ERROR,
    CONNECTION_TERMINATION_ERROR,
    CONNECTION_COMMIT_ERROR,
    CONNECTION_ROLLBACK_ERROR,
    CONNECTION_NOT_ESTABLISHED_ERROR,
    SELECT_QUERY_ERROR,
    DELETE_QUERY_ERROR,
    INSERT_QUERY_ERROR,
    UPDATE_QUERY_ERROR,
    EMPTY_STRING_ERROR,
    INPUT_OUT_OF_BOUNDS_ERROR,
    BLANK_SPOTS_IN_STRING_ERROR,
    
    PLACE_GET_ALL_ERROR,
    PLACE_EMPTY_LIST_ERROR,
    
    REGISTRATION_ERROR,
    REGISTRATION_DUPLICATE_USER_ERROR,
    
    LOGIN_ERROR,
    LOGIN_INVALID_USER_ERROR,
    
    HIKER_CREATION_ERROR,
    HIKER_INVALID_ERROR,
    HIKER_UPDATE_ERROR,
    HIKER_DELETE_ERROR,
    HIKER_GET_ALL_ERROR,
    
    SEARCH_ERROR,
    
    HIKING_GROUP_GET_ALL_ERROR,
    HIKING_GROUP_CREATION_ERROR,
    HIKING_GROUP_INVALID_ERROR,
    HIKING_GROUP_DELETE_ERROR,
    HIKING_GROUP_UPDATE_ERROR,
    
    PROFILES_GET_ALL_ERROR,
    PROFILES_SAVE_ERROR,
    PROFILES_DELETE_ERROR,
    
    GET_HIKING_GROUP_PLAN_ERROR,
    
    UNEXPECTED_ERROR,
    INVALID_INPUT_ERROR,
    INVALID_DATA_ERROR,
    SERVER_BOOT_ERROR,
    SERVER_SHUTDOWN_ERROR,
    SERVER_SOCKET_ERROR,
    SENDING_OBJECT_ERROR,
    RECEIVING_OBJECT_ERROR,
    CRITICAL_ERROR;
    
    
    
    
}
