/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.borak.hikingapp.client.view.forms;


import com.borak.hikingapp.client.logic.controllers.ControllerForms;
import com.borak.hikingapp.client.logic.controllers.Util;
import com.borak.hikingapp.commonlib.exceptions.CustomException;
import javax.swing.ImageIcon;

/**
 *
 * @author Despot
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbMain = new javax.swing.JMenuBar();
        mbGroup = new javax.swing.JMenu();
        miGroupCreate = new javax.swing.JMenuItem();
        miGroupChangeInfo = new javax.swing.JMenuItem();
        miGroupDelete = new javax.swing.JMenuItem();
        mbHiker = new javax.swing.JMenu();
        miHikerCreate = new javax.swing.JMenuItem();
        miHikerChangeInfo = new javax.swing.JMenuItem();
        miHikerDelete = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbGroup.setText("Group");

        miGroupCreate.setText("Create");
        miGroupCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGroupCreateActionPerformed(evt);
            }
        });
        mbGroup.add(miGroupCreate);

        miGroupChangeInfo.setText("Change info");
        miGroupChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGroupChangeInfoActionPerformed(evt);
            }
        });
        mbGroup.add(miGroupChangeInfo);

        miGroupDelete.setText("Delete");
        miGroupDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGroupDeleteActionPerformed(evt);
            }
        });
        mbGroup.add(miGroupDelete);

        mbMain.add(mbGroup);

        mbHiker.setText("Hiker");

        miHikerCreate.setText("Create");
        miHikerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHikerCreateActionPerformed(evt);
            }
        });
        mbHiker.add(miHikerCreate);

        miHikerChangeInfo.setText("Change info");
        miHikerChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHikerChangeInfoActionPerformed(evt);
            }
        });
        mbHiker.add(miHikerChangeInfo);

        miHikerDelete.setText("Delete");
        miHikerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHikerDeleteActionPerformed(evt);
            }
        });
        mbHiker.add(miHikerDelete);

        mbMain.add(mbHiker);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miHikerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHikerCreateActionPerformed
        ControllerForms.getInstance().openFrmHikerCreate();
    }//GEN-LAST:event_miHikerCreateActionPerformed

    private void miHikerChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHikerChangeInfoActionPerformed
       ControllerForms.getInstance().openFrmHikerChangeInfo();
    }//GEN-LAST:event_miHikerChangeInfoActionPerformed

    private void miHikerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHikerDeleteActionPerformed
       ControllerForms.getInstance().openFrmHikerDelete();
    }//GEN-LAST:event_miHikerDeleteActionPerformed

    private void miGroupCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGroupCreateActionPerformed
       ControllerForms.getInstance().openFrmGroupCreate();
    }//GEN-LAST:event_miGroupCreateActionPerformed

    private void miGroupChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGroupChangeInfoActionPerformed
       ControllerForms.getInstance().openFrmGroupChangeInfo();
    }//GEN-LAST:event_miGroupChangeInfoActionPerformed

    private void miGroupDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGroupDeleteActionPerformed
        ControllerForms.getInstance().openFrmGroupDelete();
    }//GEN-LAST:event_miGroupDeleteActionPerformed

    private void initialize() {
        setTitle("Main menu");
        try {
            ImageIcon favicon = new ImageIcon(Util.getInstance().getFrmMainFavicon());
            setIconImage(favicon.getImage());
        } catch (CustomException ex) {
            ex.printStackTrace();
        }
        
        setFormElements();
        
        setResizable(false);
        setLocationRelativeTo(null);
    }

    private void setFormElements() {
        //TODO if needed :)
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mbGroup;
    private javax.swing.JMenu mbHiker;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miGroupChangeInfo;
    private javax.swing.JMenuItem miGroupCreate;
    private javax.swing.JMenuItem miGroupDelete;
    private javax.swing.JMenuItem miHikerChangeInfo;
    private javax.swing.JMenuItem miHikerCreate;
    private javax.swing.JMenuItem miHikerDelete;
    // End of variables declaration//GEN-END:variables
}
