/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.borak.hikingapp.client.view.forms;

import com.borak.hikingapp.client.logic.controllers.ControllerForms;
import com.borak.hikingapp.client.logic.controllers.ControllerSO;
import com.borak.hikingapp.client.logic.controllers.Util;
import com.borak.hikingapp.client.view.components.CompPlaceInput;
import com.borak.hikingapp.client.view.components.CompPswInput;
import com.borak.hikingapp.client.view.components.validators.factory.ValidatorFactory;
import com.borak.hikingapp.client.view.helpers.Window;
import com.borak.hikingapp.commonlib.communication.TransferObject;
import com.borak.hikingapp.commonlib.domain.classes.Place;
import com.borak.hikingapp.commonlib.domain.classes.User;
import com.borak.hikingapp.commonlib.domain.enums.ResponseType;
import com.borak.hikingapp.commonlib.exceptions.CustomException;
import com.borak.hikingapp.commonlib.view.components.CompStringInput;
import com.borak.hikingapp.commonlib.view.components.api.IComponent;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Despot
 */
public class FrmRegister extends javax.swing.JDialog {

    private IComponent<String> firstNameComp;
    private IComponent<String> lastNameComp;
    private IComponent<String> usernameComp;
    private IComponent<String> passwordComp;
    private IComponent<String> emailComp;
    private IComponent<Place> placeComp;

    private JButton btnSave;

    private JPanel pnlComponents;
    private JPanel pnlButtons;

    public FrmRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialize() {
        setTitle("Register");
        MigLayout migMain = new MigLayout("", "[right]", "[]0[]");
        setLayout(migMain);

        try {
            ImageIcon favicon = new ImageIcon(Util.getInstance().getFrmRegisterFavicon());
            setIconImage(favicon.getImage());
        } catch (CustomException ex) {
            ex.printStackTrace();
        }

        setFormElements();

        pack();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    private void setFormElements() {
        setPanels();
        setComponents();
        setButtons();
    }

    private void setPanels() {
        MigLayout migComp = new MigLayout("", "", "[]5[]5[]5[]5[]5[]");
        MigLayout migBtn = new MigLayout("", "", "");

        pnlComponents = new JPanel(migComp);
        pnlButtons = new JPanel(migBtn);
        add(pnlComponents, "cell 0 0");
        add(pnlButtons, "cell 0 1");
    }

    private void setComponents() {

        firstNameComp = new CompStringInput(ValidatorFactory.getInstance().getUserFirstNameValidator());
        firstNameComp.setCaption("First name: ");
        firstNameComp.setCaptionWidth(100);
        firstNameComp.setInputWidth(200);
        firstNameComp.setErrorMessageWidth(200);
        firstNameComp.setErrorMessage("");

        lastNameComp = new CompStringInput(ValidatorFactory.getInstance().getUserLastNameValidator());
        lastNameComp.setCaption("Last name: ");
        lastNameComp.setCaptionWidth(100);
        lastNameComp.setInputWidth(200);
        lastNameComp.setErrorMessageWidth(200);
        lastNameComp.setErrorMessage("");

        usernameComp = new CompStringInput(ValidatorFactory.getInstance().getUserUsernameValidator());
        usernameComp.setCaption("Username: ");
        usernameComp.setCaptionWidth(100);
        usernameComp.setInputWidth(200);
        usernameComp.setErrorMessageWidth(200);
        usernameComp.setErrorMessage("");

        passwordComp = new CompPswInput(ValidatorFactory.getInstance().getUserPasswordValidator());
        passwordComp.setCaption("Password: ");
        passwordComp.setCaptionWidth(100);
        passwordComp.setInputWidth(200);
        passwordComp.setErrorMessageWidth(200);
        passwordComp.setErrorMessage("");

        emailComp = new CompStringInput(ValidatorFactory.getInstance().getUserEmailValidator());
        emailComp.setCaption("Email: ");
        emailComp.setCaptionWidth(100);
        emailComp.setInputWidth(200);
        emailComp.setErrorMessageWidth(200);
        emailComp.setErrorMessage("");

        List<Place> places;
        try {
            TransferObject response = ControllerSO.getInstance().getAllPlaces();
            if (response.getResponseType() == ResponseType.SUCCESS) {
                places = (List<Place>) response.getArgument();
                if (places == null || places.isEmpty()) {
                    placeComp = new CompPlaceInput(null, ValidatorFactory.getInstance().getPlaceValidator());
                    placeComp.setErrorMessageWidth(200);
                    placeComp.setErrorMessage("There are no places!");
                } else {
                    Place[] pom = places.toArray(new Place[0]);
                    placeComp = new CompPlaceInput(pom, ValidatorFactory.getInstance().getPlaceValidator());
                    placeComp.setErrorMessageWidth(200);
                    placeComp.setErrorMessage("");
                }
            } else {
                throw response.getException();
            }

        } catch (CustomException ex) {
            ex.printStackTrace();
            placeComp = new CompPlaceInput(null, ValidatorFactory.getInstance().getPlaceValidator());
            placeComp.setErrorMessageWidth(200);
            placeComp.setErrorMessage("Unable to retreive places!");
        }

        placeComp.setCaption("Place: ");
        placeComp.setCaptionWidth(100);
        placeComp.setInputWidth(200);

        pnlComponents.add(((JPanel) firstNameComp), "cell 0 0");
        pnlComponents.add(((JPanel) lastNameComp), "cell 0 1");
        pnlComponents.add(((JPanel) usernameComp), "cell 0 2");
        pnlComponents.add(((JPanel) passwordComp), "cell 0 3");
        pnlComponents.add(((JPanel) emailComp), "cell 0 4");
        pnlComponents.add(((JPanel) placeComp), "cell 0 5");
    }

    private void setButtons() {
        btnSave = new JButton("Save");
        btnSave.setFocusable(false);

        addListeners();

        pnlButtons.add(btnSave);
    }

    private void addListeners() {
        btnSave.addActionListener((ActionEvent e) -> {
            btnSavePressed();
        });
    }
//===============================================================================

    private void btnSavePressed() {
        firstNameComp.setErrorMessage("");
        lastNameComp.setErrorMessage("");
        usernameComp.setErrorMessage("");
        passwordComp.setErrorMessage("");
        emailComp.setErrorMessage("");
        placeComp.setErrorMessage("");

        String firstName = "";
        String lastName = "";
        String username = "";
        String password = "";
        String email = "";
        String errorMessage = "";
        Place p = null;
        boolean gate = true;

        try {
            firstName = firstNameComp.getValue();
        } catch (CustomException ex) {
            firstNameComp.setErrorMessage(ex.getMessage());
            errorMessage += ex.getMessage() + "\n";
            gate = false;
        }
        try {
            lastName = lastNameComp.getValue();
        } catch (CustomException ex) {
            lastNameComp.setErrorMessage(ex.getMessage());
            errorMessage += ex.getMessage() + "\n";
            gate = false;
        }
        try {
            username = usernameComp.getValue();
        } catch (CustomException ex) {
            usernameComp.setErrorMessage(ex.getMessage());
            errorMessage += ex.getMessage() + "\n";
            gate = false;
        }
        try {
            password = passwordComp.getValue();
        } catch (CustomException ex) {
            passwordComp.setErrorMessage(ex.getMessage());
            errorMessage += ex.getMessage() + "\n";
            gate = false;
        }
        try {
            email = emailComp.getValue();
        } catch (CustomException ex) {
            emailComp.setErrorMessage(ex.getMessage());
            errorMessage += ex.getMessage() + "\n";
            gate = false;
        }
        try {
            p = placeComp.getValue();
        } catch (CustomException ex) {
            placeComp.setErrorMessage(ex.getMessage());
            errorMessage += ex.getMessage();
            gate = false;
        }
        pack();
        if (gate) {
            User user = new User(firstName, lastName, username, password, email, p);
            try {
                TransferObject response = ControllerSO.getInstance().register(user);
                if (response.getResponseType() == ResponseType.SUCCESS) {
                    Window.successfulOperation(this, "Successful registration", "Account successfully created!");
                    ControllerForms.getInstance().closeFrmRegister();
                } else {
                    throw response.getException();
                }
            } catch (CustomException ex) {
                ex.printStackTrace();
                Window.unSuccessfulOperation(this, "Unsuccessful registration", ex.getMessage());
            }
        } else {
            Window.unSuccessfulOperation(this, "Unsuccessful registration", "Unable to register user");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
