/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.borak.hikingapp.server.view.forms;

import com.borak.hikingapp.commonlib.exceptions.CustomException;
import com.borak.hikingapp.commonlib.view.components.intf.IComponent;
import com.borak.hikingapp.server.domain.enums.DatabaseType;
import com.borak.hikingapp.server.logic.controllers.Util;
import com.borak.hikingapp.server.view.components.impl.CompDatabasePicker;
import com.borak.hikingapp.server.view.components.impl.CompStringInput;
import com.borak.hikingapp.server.view.components.validators.factory.ValidatorFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Despot
 */
public class FrmConfigurationDatabase extends javax.swing.JDialog {

    private IComponent<DatabaseType> compDatabasePicker;

    private IComponent<String> compDatabaseUrl;
    private IComponent<String> compDatabaseUsername;
    private IComponent<String> compDatabasePassword;

    private JPanel pnlPicker;
    private JPanel pnlParams;
    private JPanel pnlButtons;

    private JButton btnSave;

    public FrmConfigurationDatabase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialize() {
        setTitle("Configure database");
        MigLayout migMain = new MigLayout("insets 0 0 0 0", "[]0[]", "[]0[]");
        setLayout(migMain);
        try {
            ImageIcon favicon = new ImageIcon(Util.getInstance().getFrmConfigurationDatabaseFavicon());
            setIconImage(favicon.getImage());
        } catch (CustomException ex) {
            ex.printStackTrace();
        }

        setFormElements();

        pack();
        //setResizable(false);
        setLocationRelativeTo(null);
    }

    private void setFormElements() {
        setPanels();
        setComponents();
        setButtons();
    }

    private void setPanels() {
        MigLayout migPicker = new MigLayout("insets 0 0 0 0", "", "");
        MigLayout migButtons = new MigLayout("insets 0 0 0 0", "", "");
        MigLayout migParams = new MigLayout("insets 0 0 0 0", "", "[]0[]0[]");

        pnlPicker = new JPanel(migPicker);
        pnlButtons = new JPanel(migButtons);
        pnlParams = new JPanel(migParams);

        add(pnlPicker, "cell 0 0");
        add(pnlButtons, "cell 1 0");
        add(pnlParams, "cell 0 1 2 1");
    }

    private void setComponents() {
        setDatabasePicker();
        setDatabaseParams();
    }

    private void setDatabasePicker() {
        compDatabasePicker = new CompDatabasePicker();
        compDatabasePicker.setCaption("Database:");
        compDatabasePicker.setCaptionSize(100);
        compDatabasePicker.setErrorMessageSize(200);
        compDatabasePicker.setInputSize(200);
        compDatabasePicker.setErrorMessage("");
        
        try {
            String currentDB = Util.getInstance().getCurrentDatabase();
            DatabaseType t = DatabaseType.parseDatabaseType(currentDB);
            compDatabasePicker.setValue(t);
        } catch (CustomException ex) {
            ex.printStackTrace();
        }

        ((CompDatabasePicker) compDatabasePicker).addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cbPickerPressed();
                
            }

        });

        

        pnlPicker.add((JPanel) compDatabasePicker, "cell 0 0");
    }

    private void setDatabaseParams() {
        compDatabaseUrl = new CompStringInput(ValidatorFactory.getInstance().getDatabaseUrlValidator());
        compDatabaseUsername = new CompStringInput(ValidatorFactory.getInstance().getDatabaseUsernameValidator());
        compDatabasePassword = new CompStringInput(ValidatorFactory.getInstance().getDatabasePasswordValidator());

        compDatabaseUrl.setCaption("Url:");
        compDatabaseUrl.setCaptionSize(70);
        compDatabaseUrl.setErrorMessageSize(200);
        compDatabaseUrl.setInputSize(250);
        compDatabaseUrl.setErrorMessage("");

        compDatabaseUsername.setCaption("Username:");
        compDatabaseUsername.setCaptionSize(70);
        compDatabaseUsername.setInputSize(250);
        compDatabaseUsername.setErrorMessageSize(200);
        compDatabaseUsername.setErrorMessage("");

        compDatabasePassword.setCaption("Password:");
        compDatabasePassword.setCaptionSize(70);
        compDatabasePassword.setInputSize(250);
        compDatabasePassword.setErrorMessageSize(200);
        compDatabasePassword.setErrorMessage("");

        fillParams();

        pnlParams.add((JPanel) compDatabaseUrl, "cell 0 0");
        pnlParams.add((JPanel) compDatabaseUsername, "cell 0 1");
        pnlParams.add((JPanel) compDatabasePassword, "cell 0 2");
    }

    private void setButtons() {
        btnSave = new JButton("Save");

        btnSave.setFocusable(false);
        btnSave.addActionListener((e) -> {
            btnSavePressed();
        });
        pnlButtons.add(btnSave, "cell 0 0");
    }

    private void btnSavePressed() {
        //TODO
    }

    public void cbPickerPressed() {
        try {
            DatabaseType t = compDatabasePicker.getValue();
            if (t.hasParams()) {
                pnlParams.setVisible(true);
            } else {
                pnlParams.setVisible(false);
            }
            this.pack();
        } catch (CustomException ex) {
            ex.printStackTrace();
        }
    }

    private void fillParams() {
        try {
            String url = Util.getInstance().getDatabaseUrl();
            compDatabaseUrl.setValue(url);
            String username = Util.getInstance().getDatabaseUsername();
            compDatabaseUsername.setValue(username);
            String password = Util.getInstance().getDatabasePassword();
            compDatabasePassword.setValue(password);
        } catch (CustomException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
