/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.borak.hikingapp.commonlib.view.components.design;

import com.borak.hikingapp.commonlib.view.components.api.IComponent;
import com.borak.hikingapp.commonlib.view.components.validators.api.IValidator;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Despot
 */
public abstract class CompThreeComboBox<ComponentType, ComboBoxesType, ValidatorType> extends javax.swing.JPanel implements IComponent<ComponentType> {

    private JLabel lblCaption;
    private JLabel lblErrorMessage;
    private JLabel lbl1;
    private JLabel lbl2;
    private JLabel lbl3;
    protected JComboBox<ComboBoxesType> cb1;
    protected JComboBox<ComboBoxesType> cb2;
    protected JComboBox<ComboBoxesType> cb3;
    protected IValidator<ValidatorType> validator;

    public CompThreeComboBox(String firstLabel, String secondLabel, String thirdLabel, IValidator validator) {
        initComponents();
        this.validator = validator;
        initialize(firstLabel, secondLabel, thirdLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initialize(String firstLabel, String secondLabel, String thirdLabel) {
        MigLayout mig = new MigLayout("insets 0 0 0 0", "[]10[]10[]10[]", "[]0[]0[]");
        setLayout(mig);
        setComponents(firstLabel, secondLabel, thirdLabel);
    }

    private void setComponents(String firstLabel, String secondLabel, String thirdLabel) {

        setCaption();
        setFirstLabel(firstLabel);
        setSecondLabel(secondLabel);
        setThirdLabel(thirdLabel);
        setFirstCB();
        setSecondCB();
        setThirdCB();
        setErrorMessage();

        add(lblCaption, "cell 0 1");
        add(lbl1, "cell 1 0,align center");
        add(lbl2, "cell 2 0,align center");
        add(lbl3, "cell 3 0,align center");
        add(cb1, "cell 1 1");
        add(cb2, "cell 2 1");
        add(cb3, "cell 3 1");
        add(lblErrorMessage, "cell 1 2 3 1");// "cell column row width height"

    }

    private void setCaption() {
        lblCaption = new JLabel("Caption");
//        Dimension d = lblCaption.getPreferredSize();
//        int width = (int) d.getWidth();
//        int height = (int) d.getHeight();
//        lblCaption.setPreferredSize(new Dimension(100, height));
    }

    private void setErrorMessage() {
        lblErrorMessage = new JLabel("ErrorMessage");
//        Dimension d = lblErrorMessage.getPreferredSize();
//        int width = (int) d.getWidth();
//        int height = (int) d.getHeight();
//        lblErrorMessage.setPreferredSize(new Dimension(200, height));
        lblErrorMessage.setForeground(Color.red);
    }

    private void setFirstLabel(String firstLabel) {
        lbl1 = new JLabel(firstLabel);
//        Dimension d = lbl1.getPreferredSize();
//        int width = (int) d.getWidth();
//        int height = (int) d.getHeight();
//        lbl1.setPreferredSize(new Dimension(width, height));
    }

    private void setSecondLabel(String secondLabel) {
        lbl2 = new JLabel(secondLabel);
//        Dimension d = lbl2.getPreferredSize();
//        int width = (int) d.getWidth();
//        int height = (int) d.getHeight();
//        lbl2.setPreferredSize(new Dimension(width, height));
    }

    private void setThirdLabel(String thirdLabel) {
        lbl3 = new JLabel(thirdLabel);
//        Dimension d = lbl3.getPreferredSize();
//        int width = (int) d.getWidth();
//        int height = (int) d.getHeight();
//        lbl3.setPreferredSize(new Dimension(width, height));
    }

//=================================================================================
    private void setFirstCB() {
        cb1 = new JComboBox<>();
//        Dimension d = cb1.getPreferredSize();
//        int width = (int) d.getWidth();
//        int height = (int) d.getHeight();
//        cb1.setPreferredSize(new Dimension(width, height));
    }

    private void setSecondCB() {
        cb2 = new JComboBox<>();
//        Dimension d = cb2.getPreferredSize();
//        int width = (int) d.getWidth();
//        int height = (int) d.getHeight();
//        cb2.setPreferredSize(new Dimension(width, height));
    }

    private void setThirdCB() {
        cb3 = new JComboBox<>();
//        Dimension d = cb3.getPreferredSize();
//        int width = (int) d.getWidth();
//        int height = (int) d.getHeight();
//        cb3.setPreferredSize(new Dimension(width, height));
    }
//===============================METHODS=========================================
//-------------------------------CAPTION-----------------------------------------

    @Override
    public void setCaption(String caption) {
        lblCaption.setText(caption);
    }

    @Override
    public void setCaption(String[] caption) {
        caption = formatArrayString(caption);
        if (caption != null && caption.length > 0) {
            for (int i = 0; (i < caption.length && i < 4); i++) {
                switch (i) {
                    case 0 ->
                        lblCaption.setText(caption[i]);
                    case 1 ->
                        lbl1.setText(caption[i]);
                    case 2 ->
                        lbl2.setText(caption[i]);
                    case 3 ->
                        lbl3.setText(caption[i]);
                    default -> {
                    }
                }
            }
        }
    }

    @Override
    public void setCaptionSize(int width) {
        Dimension d = lblCaption.getPreferredSize();
        d.setSize(width, d.getHeight());
        lblCaption.setPreferredSize(d);
    }

    @Override
    public void setCaptionSize(int width, int height) {
        lblCaption.setPreferredSize(new Dimension(width, height));
    }
//-----------------------------ERROR MESSAGE-------------------------------------

    @Override
    public void setErrorMessage(String errorMessage) {
        lblErrorMessage.setText(errorMessage);
    }

    @Override
    public void setErrorMessageSize(int width) {
        Dimension d = lblErrorMessage.getPreferredSize();
        d.setSize(width, d.getHeight());
        lblErrorMessage.setPreferredSize(d);
    }

    @Override
    public void setErrorMessageSize(int width, int height) {
        lblErrorMessage.setPreferredSize(new Dimension(width, height));
    }
//----------------------------INPUT----------------------------------------------

    @Override
    public void setInputSize(int width) {
        Dimension d1 = cb1.getPreferredSize();
        Dimension d2 = cb2.getPreferredSize();
        Dimension d3 = cb3.getPreferredSize();

        d1.setSize(width, d1.getHeight());
        d2.setSize(width, d2.getHeight());
        d3.setSize(width, d3.getHeight());

        cb1.setPreferredSize(d1);
        cb2.setPreferredSize(d2);
        cb3.setPreferredSize(d3);

    }

    @Override
    public void setInputSize(int width, int height) {
        cb1.setPreferredSize(new Dimension(width, height));
        cb2.setPreferredSize(new Dimension(width, height));
        cb3.setPreferredSize(new Dimension(width, height));
    }

    @Override
    public void setInputSize(Integer[] width) {
        width = formatArray(width);
        if (width != null && width.length > 0) {
            for (int i = 0; i < width.length && i < 3; i++) {
                switch (i) {
                    case 0 -> {
                        Dimension d1 = cb1.getPreferredSize();
                        d1.setSize(width[i], d1.getHeight());
                        cb1.setPreferredSize(d1);
                    }
                    case 1 -> {
                        Dimension d2 = cb2.getPreferredSize();
                        d2.setSize(width[i], d2.getHeight());
                        cb2.setPreferredSize(d2);
                    }
                    case 2 -> {
                        Dimension d3 = cb3.getPreferredSize();
                        d3.setSize(width[i], d3.getHeight());
                        cb3.setPreferredSize(d3);
                    }
                    default -> {
                    }
                }
            }
        }
    }

    @Override
    public void setInputSize(Integer[] width, Integer[] height) {
        width = formatArray(width);
        height = formatArray(height);

        if ((width != null && width.length > 0) && (height != null && height.length > 0)) {
            //both width and height got atleast 1 element
            Dimension d;
            for (int i = 0; i < findMax(width.length, height.length) && i < 3; i++) {
                switch (i) {
                    case 0 ->
                        cb1.setPreferredSize(new Dimension(width[i], height[i]));
                    case 1 -> {
                        if (i >= width.length) {
                            d = cb2.getPreferredSize();
                            d.setSize(d.getWidth(), height[i]);
                            cb2.setPreferredSize(d);
                        } else if (i >= height.length) {
                            d = cb2.getPreferredSize();
                            d.setSize(width[i], d.getHeight());
                            cb2.setPreferredSize(d);
                        } else {
                            cb2.setPreferredSize(new Dimension(width[i], height[i]));
                        }
                    }
                    case 2 -> {
                        if (i >= width.length) {
                            d = cb3.getPreferredSize();
                            d.setSize(d.getWidth(), height[i]);
                            cb3.setPreferredSize(d);
                        } else if (i >= height.length) {
                            d = cb3.getPreferredSize();
                            d.setSize(width[i], d.getHeight());
                            cb3.setPreferredSize(d);
                        } else {
                            cb3.setPreferredSize(new Dimension(width[i], height[i]));
                        }
                    }
                    default -> {
                    }
                }
            }
        } else if (width != null && width.length > 0) {
            //only width has atleast 1 element
            Dimension d;
            for (int i = 0; (i < width.length && i < 3); i++) {
                switch (i) {
                    case 0 -> {
                        d = cb1.getPreferredSize();
                        d.setSize(width[i], d.getHeight());
                        cb1.setPreferredSize(d);
                    }
                    case 1 -> {
                        d = cb2.getPreferredSize();
                        d.setSize(width[i], d.getHeight());
                        cb2.setPreferredSize(d);
                    }

                    case 2 -> {
                        d = cb3.getPreferredSize();
                        d.setSize(width[i], d.getHeight());
                        cb3.setPreferredSize(d);
                    }
                    default -> {
                    }
                }
            }
        } else if (height != null && height.length > 0) {
            //only height has atleast 1 element
            Dimension d;
            for (int i = 0; (i < height.length && i < 3); i++) {
                switch (i) {
                    case 0 -> {
                        d = cb1.getPreferredSize();
                        d.setSize(d.getWidth(), height[i]);
                        cb1.setPreferredSize(d);
                    }
                    case 1 -> {
                        d = cb2.getPreferredSize();
                        d.setSize(d.getWidth(), height[i]);
                        cb2.setPreferredSize(d);
                    }
                    case 2 -> {
                        d = cb3.getPreferredSize();
                        d.setSize(d.getWidth(), height[i]);
                        cb3.setPreferredSize(d);
                    }
                    default -> {
                    }
                }
            }
        }
    }

    @Override
    public void setBackgroundColor(Color color) {
        setBackground(color);
    }

    @Override
    public void setEnabledInput(boolean isEnabled) {
        cb1.setEnabled(isEnabled);
        cb2.setEnabled(isEnabled);
        cb3.setEnabled(isEnabled);
    }

//================================================================================
    private int findMax(int a, int b) {
        return a > b ? a : b;
    }

    private Integer[] formatArray(Integer[] n) {
        if (n == null || n.length == 0) {
            return n;
        }
        List<Integer> list = new ArrayList<>(n.length);
        for (Integer n1 : n) {
            if (n1 != null) {
                list.add(n1);
            }
        }
        return list.toArray(Integer[]::new);
    }

    private String[] formatArrayString(String[] n) {
        if (n == null || n.length == 0) {
            return n;
        }
        List<String> list = new ArrayList<>(n.length);
        for (String n1 : n) {
            if (n1 != null) {
                list.add(n1);
            }
        }
        return list.toArray(String[]::new);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
